/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      "xs": "320px",
      "sm": "640px",
      "md": "768px",
      "lg": "1024px",
      "xl": "1280px",
    },
    extend: {
      colors: {
        "on-tertiary-fixed": "#301400",
        "primary": "#2D4B31",
        "tertiary-fixed": "#ffdcc5",
        "surface-bright": "#fcf9f2",
        "on-secondary-container": "#794f15",
        "background": "#fcf9f2",
        "primary-fixed": "#c8ecc8",
        "secondary": "#80551b",
        "on-surface": "#1c1c18",
        "tertiary": "#4c2300",
        "surface-dim": "#dcdad3",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#2a1700",
        "surface-container": "#f1eee7",
        "surface-container-highest": "#e5e2db",
        "primary-container": "#2d4b31",
        "on-primary-fixed": "#03210b",
        "on-tertiary-fixed-variant": "#713700",
        "primary-fixed-dim": "#adcfad",
        "secondary-fixed": "#ffddb8",
        "surface-tint": "#2D4B31",
        "on-tertiary": "#ffffff",
        "outline": "#737971",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#2f4e33",
        "surface-container-low": "#f6f3ec",
        "surface-container-high": "#ebe8e1",
        "error": "#ba1a1a",
        "inverse-primary": "#adcfad",
        "surface": "#fcf9f2",
        "on-surface-variant": "#424841",
        "tertiary-fixed-dim": "#ffb783",
        "surface-variant": "#e5e2db",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#653e03",
        "inverse-surface": "#31312c",
        "on-error-container": "#93000a",
        "tertiary-container": "#6d3500",
        "on-background": "#1c1c18",
        "secondary-container": "#fec47f",
        "inverse-on-surface": "#f3f0e9",
        "on-primary-container": "#98ba99",
        "on-tertiary-container": "#ff9846",
        "outline-variant": "#c2c8bf",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#f5bc78"
      },
      fontFamily: {
        "headline": ["Epilogue"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: { "DEFAULT": "0.5rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
